apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.2.4
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 636
          name: ldaps
        volumeMounts:
          - name: openldap-pv
            mountPath: /etc/ldap/slapd.d
            subPath: etc-ldap
          - name: openldap-pv
            mountPath: /var/lib/ldap
            subPath: var-ldap
        resources:
      volumes:
        - name: openldap-pv
          persistentVolumeClaim:
            claimName: openldap-pvc