apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
  labels:
    app: openldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: 'hostpath'