apiVersion: v1
kind: Service
metadata:
  name: openldap
spec:
  type: NodePort
  selector:
    app: openldap
  ports:
  - port: 389
    targetPort: ldap
    name: ldap
    nodePort: 31110
  - port: 636
    targetPort: ldaps
    name: ldaps
    nodePort: 31111
