apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-pv
            mountPath: /var/lib/mysql
        resources: 
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc