apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranger-admin
spec:
  selector:
    matchLabels:
      app: ranger-admin
  template:
    metadata:
      labels:
        app: ranger-admin
    spec:
      containers:
      - name: ranger-admin
        image: ranger-admin
        imagePullPolicy: Never
        env:
          - name: MYSQL_HOST
            value: $(MYSQL_SERVICE):3306
          - name: MYSQL_ROOT_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
        - containerPort: 6080
          name: http
        resources:
      - name: ranger-usersync
        image: ranger-usersync
        imagePullPolicy: Never
        env:
          - name: SYNC_LDAP_URL
            value: ldap://$(OPENLDAP_SERVICE)
          - name: POLICY_MGR_URL
            value: http://localhost:6080
        envFrom:
          - configMapRef:
              name: ranger-usersync