apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
spec:
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
      - name: namenode
        image: hadoop-namenode-ranger
        imagePullPolicy: Never
        env:
          - name: CLUSTER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: HDFS_CONF_hadoop_security_group_mapping_ldap_url
            value: ldap://$(OPENLDAP_SERVICE)
          - name: POLICY_MGR_URL
            value: http://$(RANGER_ADMIN_SERVICE):6080
        envFrom:
          - configMapRef:
              name: hdfs-ldap
        ports:
          - containerPort: 8020
            name: fs
          - containerPort: 50070
            name: http
          - containerPort: 50470
            name: https
        volumeMounts:
          - name: hdfs-name-pv
            mountPath: /hadoop/dfs/name
        resources:
      volumes:
        - name: hdfs-name-pv
          persistentVolumeClaim:
            claimName: hdfs-name-pvc