apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-name-pvc
  labels:
    app: namenode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: 'hostpath'