apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  type: NodePort
  selector:
    app: namenode
  ports:
  - port: 8020
    targetPort: fs
    name: fs
    nodePort: 31101
  - port: 50070
    targetPort: http
    name: http
    nodePort: 31100
