apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
spec:
  serviceName: datanode
  replicas: 3
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: hadoop-datanode
        imagePullPolicy: Never
        env:
          - name: CORE_CONF_fs_defaultFS
            value: hdfs://$(NAMENODE_SERVICE):8020
          - name: HDFS_CONF_dfs_datanode_address
            value: 0.0.0.0:50010
          - name: HDFS_CONF_dfs_datanode_ipc_address
            value: 0.0.0.0:50020
          - name: HDFS_CONF_dfs_datanode_http_address
            value: 0.0.0.0:50075
          - name: HDFS_CONF_hadoop_security_group_mapping_ldap_url
            value: ldap://$(OPENLDAP_SERVICE)
        envFrom:
          - configMapRef:
              name: hdfs-ldap
        ports:
          - containerPort: 50010
            name: data
          - containerPort: 50020
            name: ipc
          - containerPort: 50075
            name: http
        volumeMounts:
          - name: hdfs-data-pv
            mountPath: /hadoop/dfs/data
  volumeClaimTemplates:
    - metadata:
        name: hdfs-data-pv
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 10Gi